version: '3.8'

services:

  # Backend Service (Spring Boot)
  backend:
    build:
      context: .  # Set context to root to access pom.xml
      dockerfile: src/Dockerfile # Specify the path to your Dockerfile
    container_name: backend-container
    networks:
      - app-network
    environment:
      - DB_SERVER=database
      - POSTGRES_DB=websiteDb  # adjust to your database name
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hejhej
    depends_on:
      - database
    ports:
      - "8080:8080"

  # Frontend Service (Angular)
  frontend:
    build:
      context: ./frontend-angular  # Path to your frontend Dockerfile located in frontend-angular
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "4200:3000"
    links:
      - backend

  # PostgreSQL Database Service
  database:
    image: postgres:latest  # Use the latest version of Postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: websiteDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hejhej
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

# Define a shared network for communication between containers
networks:
  app-network:
    driver: bridge

# Data volume for persistent database storage
volumes:
  postgres-data: